config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'traceries#index'
  get '/traceries/all', to: 'traceries#all'
  get '/traceries/edit/:id', to: 'traceries#edit', as: 'traceries_edit'
  patch '/traceries/update/:id', to: 'traceries#update', as: 'traceries_update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :legendaries
end

app/models/legendary.rb
class Legendary < ApplicationRecord
  belongs_to :character
  has_many :traceries
end

app/models/tracery.rb
class Tracery < ApplicationRecord
  belongs_to :legendary
  belongs_to :tracery_color

  def character_name
    self.legendary.character.name
  end
end

app/models/tracery_color.rb
class TraceryColor < ApplicationRecord
  has_one :tracery
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :turbo_frame_request_variant

  private

  def turbo_frame_request_variant
    request.variant = :turbo_frame if turbo_frame_request?
  end
end

app/controllers/traceries_controller.rb
class TraceriesController < ApplicationController
  def index
    if params[:query].present?
      @traceries = Tracery.where("name LIKE ?", "%#{params[:query]}%").includes(legendary: :character).includes(:tracery_color)
    else
      @traceries = Tracery.all.includes(legendary: :character).includes(:tracery_color)
    end
  end

  def all
    @characters = Character.all.includes(legendaries: { traceries: :tracery_color } )
  end

  def edit
    @tracery = Tracery.find(params[:id])
    @tracery_colors = TraceryColor.all
  end

  def update
    tparams = params[:tracery]
    @tracery = Tracery.find(params[:id])
    if !@tracery.update(
      name: tparams[:name],
      tracery_color: TraceryColor.find(tparams[:tracery_color_id].to_i),
      level: tparams[:level],
      tracery_type: tparams[:tracery_type])
      Rails.logger.error(@tracery.errors.inspect)
    end
    flash[:notice] = "'#{@tracery.name}' tracery was updated successfully"
    redirect_to traceries_all_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TraceryMonitor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/traceries/_edit.html.erb
<div>
  <div>
  <%# form_with model: @tracery, url: tracery_path(@tracery), method: :patch do |f| %>
  <%= form_with(model: @tracery, url: traceries_all_path, id: "tracery_edit_form", data: { extended_modal_target: 'form' }) do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <br>
    <%= form.submit %>
    <button data-action="click->extended-modal#close">
    Cancel
    </button>
  <% end %>
  </div>
</div>

app/views/traceries/_form.html.erb
<div>
  <div>
  <%# form_with model: @tracery, url: tracery_path(@tracery), method: :patch do |f| %>
  <%= form_with(model: @tracery, url: traceries_all_path, id: "tracery_edit_form", data: { extended_modal_target: 'form' }) do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <br>
    <%= form.submit %>
    <button data-action="click->extended-modal#close">
    Cancel
    </button>
  <% end %>
  </div>
</div>

app/views/traceries/_modal.html.erb
<div data-extended-modal-target="container"
     data-action="turbo:submit-end->extended-modal#handleSuccess"
     class="hidden animated fadeIn fixed inset-0 overflow-y-auto flex items-center justify-center"
     style="z-index: 9999;">
  <div class="max-w-lg max-h-screen w-full relative">
    <div class="m-1 bg-white rounded shadow">
      <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
        <h3 class="text-lg leading-6 font-medium text-gray-800">
          Edit Tracery
        </h3>
      </div>
      <form id="tracery_edit_form"></form>
    </div>
  </div>
</div>

app/views/traceries/_traceries.html.erb
<%= turbo_frame_tag "traceries" do %>
  <%= render traceries %>
<% end %>

app/views/traceries/_tracery.html.erb
<div id="<%= dom_id tracery %>" class="grid grid-cols-3 gap-3 p-1">
  <div><%= tracery.character_name %></div>
  <div><%= tracery.legendary.name %></div>
  <div style="background-color: #<%= tracery.tracery_color.hex %>"><%= tracery.name %></div>
</div>

app/views/traceries/all.html.erb
<div class="max-w-4xl mx-auto">

<div class="grid grid-cols-1 pt-8 pb-4">
<p style="color: green" class="text-center pb-4"><%= notice %></p>
  <div class="pb-4 content-center">
    <p center class="text-center font-extrabold text-2xl">All Traceries</p>
  </div>

  <div class="text-center pb-4"><%= link_to "Search Traceries", root_path, class: "text-cyan-600" %></div>

</div>

<div class="max-w-5xl mx-auto">
  <% if @characters.count > 0 %>
  <% @characters.each do |c| %>
    <p class="text-center font-extrabold text-xl p-4"><%= c.name %></p><!-- Style this better -->
    <div class="grid grid-cols-2 gap-4">
    <% c.legendaries.each do |li| %>
      <div>
      <div class="bg-gray-800 text-white p-2">
        <%= li.name %>: <%= li.li_type %> (Rank <%= li.rank %>)
      </div>
      <% li.traceries.each do |t| %>
        <div style="background-color: #<%= t.tracery_color.hex %>" class="pl-4 pr-4 py-1">
          <%= t.name %>
          <span class="float-right"><%= link_to "edit", traceries_edit_path(t), class: "text-cyan-600" %></span>
        </div>
      <% end %>
      </div>
    <% end %>
    </div>
  <% end %>
  <% end %>
</div>

app/views/traceries/edit.html.erb
<div class="max-w-4xl mx-auto">
<div class="grid grid-cols-1 pt-8 pb-4">
  <div class="pb-4 content-center">
    <p center class="text-center font-extrabold text-xl pb-4">Edit Tracery</p>

  <div class="text-center pb-4">
  <%= form_with model: @tracery, url: traceries_update_path(@tracery), method: :patch do |f| %>
      <div class="grid grid-cols-2">
      <div class="pb-4"><p class="text-right pr-3">
      <%= f.label :name, "Name:" %></p></div>
      <div class="pb-4"><p class="text-left"><%= f.text_field :name, class: "pl-2 p-1 shadow appearance-none border rounded text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %></p></div>

      
      <div class="pb-4"><p class="text-right pr-3"><%= f.label :tracery_color, "Tracery Color:" %></p></div>
      <div class="pb-4"><p class="text-left">
        <%= f.select :tracery_color_id, @tracery_colors.map {|c| [c.name, c.id] }, {}, id: "tracery_color_id", class: "pl-2 p-1 shadow border rounded text-gray-700 focus:outline-none focus:shadow-outline" %>

      <div class="pb-4"><p class="text-right pr-3"><%= f.label :level, "Level:" %></p></div>
      <div class="pb-4"><p class="text-left">
      <%= f.text_field :level, class: "pl-2 p-1 shadow appearance-none border rounded text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="pb-4"><p class="text-right pr-3"><%= f.label :tracery_type, "Tracery Type:" %></p></div>
      <div class="pb-4"><p class="text-left">
      <%= f.text_field :tracery_type, class: "pl-2 p-1 shadow appearance-none border rounded text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %></p></div>
      </div>

      <div class="pb-4">
      <%= f.submit "Update", class: "bg-cyan-500 hover:bg-cyan-700 text-white font-bold py-1 px-3 rounded focus:outline-none focus:shadow-outline" %>
      </div>
  <% end %>
  </div>
  </div>
</div>
</div>

app/views/traceries/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="max-w-4xl mx-auto">

<div class="grid grid-cols-1 pt-8 pb-4">
  <div class="pb-4 content-center">
    <p center class="text-center font-extrabold text-xl">Search Traceries</p>
  </div>

  <div class="text-center pb-4">
  <%= form_with(url: root_path, method: "GET", data: { controller: "form-submission", turbo_frame: "traceries" }) do |form| %>
    <%= form.label :query, "Search by name:" %>
    <%= form.text_field :query, data: { action: "input->form-submission#search" }, class: "pl-2 p-1 shadow appearance-none border rounded text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <%= form.submit 'Search', name: nil, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-1 px-3 rounded focus:outline-none focus:shadow-outline" %>
  <% end %>
  </div>
  <div class="text-center pb-4"><%= link_to "All traceries", traceries_all_path, class: "text-cyan-600" %></div>
</div>

  <div class="shadow overflow-hidden rounded border-b border-gray-200">
    <div class="grid grid-cols-3 gap-3 bg-gray-800 text-white p-2"> <!-- table -->
      <div>Character Name</div>
      <div>LI Name</div>
      <div>Tracery Name</div>
    </div>
    <%= render "traceries", traceries: @traceries %>
  </div>
</div>